imports:
    - { resource: config_dev.yml }
    - { resource: fixtures.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
  dbal:
    driver: 'pdo_sqlite'
    path: '%kernel.cache_dir%/db.sqlite'
    charset: 'UTF8'


