production:
  entity: \Ivoz\Provider\Domain\Model\BalanceMovement\BalanceMovement
  fields: 
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
    carrier:
      title: ngettext('Carrier', 'Carriers', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Carrier\Carrier
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Carrier.name: asc
    amount:
      title: _('Movement amount')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_BalanceMovements
        method: getAmount
    balance:
      title: _('Balance')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_BalanceMovements
        method: getBalance
    createdOn:
      title: _('Created')
      type: picker
      readonly: true
      source:
        control: datetime
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
