production:
  entity: Ivoz\Provider\Domain\Model\CallCsvScheduler\CallCsvScheduler
  fields:
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      maxLength: 40
      default: true
    frequency:
      title: _('Frequency')
      type: number
      required: true
      defaultValue: 1
      source:
        control: Spinner
        min: 1
    unit:
      title: _('Unit')
      type: select
      required: true
      defaultValue: 'month'
      source:
        data: inline
        values:
          'day': _('Day')
          'week': _('Week')
          'month': _('Month')
    email:
      title: ngettext('Email', 'Emails', 1)
      type: text
      trim: both
      defaultValue: ''
      maxLength: 140
      info:
        type: box
        position: left
        icon: help
        text: _("Leave empty if no mail is needed (just generate CSV).")
        label: _("Need help?")
      default: true
    lastExecution:
      title: _('Last execution')
      type: ghost
      dirty: true
      source:
        class: IvozProvider_Klear_Ghost_SchedulerSuccess
        method: getCallCsvSchedulerLastExecutionReport
    nextExecution:
      title: _('Next execution')
      type: picker
      required: true
      source:
        control: datetime
        settings:
          disabled: 'false'
    brand:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Brand.name: asc
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      source:
        data: mapper
        'null': _("All clients")
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
          visualFilter:
            name:
              __default__:
                show: []
                hide: ["callCsvNotificationTemplate"]
              'null':
                show: ["callCsvNotificationTemplate"]
                hide: []
    callCsvNotificationTemplate:
      title: ngettext('Notification template', 'Notification templates', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplate
          filterClass: IvozProvider_Klear_Filter_NotificationTemplateCallCsv
          fieldName:
            fields:
            - name
            template: '%name%'
        'null': _("Use generic template")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
