production:
  entity: Ivoz\Provider\Domain\Model\DestinationRate\DestinationRate
  fields: 
    id:
      title: ngettext('Id', 'Ids', 1)
      required: false
      default: true
    connectFee:
      title: _('Connection fee')
      type: text
      pattern: "^[0-9]{1,6}[.]{0,1}[0-9]*$"
      trim: both
      required: true
      defaultValue: "0.0000"
      info:
        type: box
        position: left
        icon: help
        text: _("Use point as decimal delimiter - e.g. 0.02")
        label: _("Need help?")
    connectFeeCurrency:
      title: _('Connection fee')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_DestinationRates
        method: getConnectFee
    cost:
      title: _('Per minute rate')
      type: text
      pattern: "^[0-9]{1,6}[.]{0,1}[0-9]*$"
      trim: both
      required: true
      defaultValue: "0.0000"
      info:
        type: box
        position: left
        icon: help
        text: _("Use point as decimal delimiter - e.g. 0.02")
        label: _("Need help?")
    costCurrency:
      title: _('Per minute rate')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_DestinationRates
        method: getCost
    rateIncrement:
      title: _('Charge period')
      type: number
      defaultValue: 1
      required: true
      source:
        control: Spinner
        min: 1
        step: 1
      info:
        type: box
        position: left
        icon: help
        text: _("Interval in seconds to increase call cost.")
        label: _("Need help?")
    groupIntervalStart:
      title: _('Interval start')
      type: number
      defaultValue: 0
      required: true
      source:
        control: Spinner
        min: 0
        step: 1
      info:
        type: box
        position: left
        icon: help
        text: _("Seconds from the beginning of the call when this rate will be activated.")
        label: _("Need help?")
    destinationRateGroup:
      title: ngettext('Destination rate group', 'Destination rate groups', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\DestinationRateGroup\DestinationRateGroup
          fieldName:
            fields:
              - id
            template: "%name${lang}%"
    destination:
      title: ngettext('Destination', 'Destinations', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Destination\Destination
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name${lang}
              - prefix
            template: "%name${lang}% (%prefix%)"
      decorators:
        autocomplete:
          command: destinationsRatesautocomplete_command

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
