########################################
## Raw
########################################
Ivoz\Provider\Domain\Model\Brand\Brand:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        id:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Brand\Invoice:
Ivoz\Provider\Domain\Model\Brand\Logo:
Ivoz\Provider\Domain\Model\BalanceNotification\BalanceNotification:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        company:
          in: "companyRepository.getSupervisedCompanyIdsByAdmin(user)"
Ivoz\Provider\Domain\Model\BrandService\BrandService:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\BrandUrl\BrandUrl:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Company\Company:
  attributes:
    access_control: '"ROLE_COMPANY_ADMIN" in roles'
    read_access_control:
      ROLE_COMPANY_ADMIN:
        company:
          eq: "user.getCompany().getId()"
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Country\Name:
Ivoz\Provider\Domain\Model\Country\Zone:
Ivoz\Provider\Domain\Model\Country\Country:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
Ivoz\Provider\Domain\Model\Domain\Domain:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\DdiProvider\DdiProvider:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\DdiProviderRegistration\DdiProviderRegistration:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      inherited:
        ddiProvider: 'Ivoz\Provider\Domain\Model\DdiProvider\DdiProvider'
Ivoz\Provider\Domain\Model\DdiProviderAddress\DdiProviderAddress:
    attributes:
      access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      inherited:
        ddiProvider: 'Ivoz\Provider\Domain\Model\DdiProvider\DdiProvider'
Ivoz\Provider\Domain\Model\Feature\Feature:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrand:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\FixedCost\FixedCost:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoice:
  collectionOperations:
    get:
      operation_normalization_context: 'detailedCollection'
      normalization_context:
        groups: ['detailedCollection']
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      inherited:
        fixedCost: 'Ivoz\Provider\Domain\Model\FixedCost\FixedCost'
Ivoz\Provider\Domain\Model\Invoice\Invoice:
  attributes:
    access_control: '"ROLE_COMPANY_ADMIN" in roles'
    read_access_control:
      ROLE_COMPANY_ADMIN:
        company:
          eq: "user.getCompany().getId()"
      ROLE_BRAND_ADMIN:
        company:
          in: "companyRepository.getSupervisedCompanyIdsByAdmin(user)"
Ivoz\Provider\Domain\Model\InvoiceNumberSequence\InvoiceNumberSequence:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\InvoiceTemplate\InvoiceTemplate:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Language\Language:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
Ivoz\Provider\Domain\Model\Language\Name:
Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplate:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\NotificationTemplateContent\NotificationTemplateContent:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      inherited:
        notificationTemplate: 'Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplate'
Ivoz\Provider\Domain\Model\Carrier\Carrier:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\CarrierServer\CarrierServer:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroup:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPattern:
  collectionOperations:
    get:
      operation_normalization_context: 'detailedCollection'
      normalization_context:
        groups: ['detailedCollection']
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      inherited:
        routingPatternGroup: 'Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroup'
Ivoz\Provider\Domain\Model\RoutingPattern\Name:
Ivoz\Provider\Domain\Model\RoutingPattern\Description:
Ivoz\Provider\Domain\Model\RoutingPattern\RoutingPattern:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Service\Service:
  itemOperations:
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Timezone\Timezone:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSet:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\TransformationRule\TransformationRule:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      inherited:
        transformationRuleSet: 'Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSet'
