#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include BillableCallsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: billableCallsList_screen

  screens:
    <<: *billableCalls_screensLink
    billableCallsList_screen:
      <<: *billableCallsList_screenLink
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/calls/billable_calls.html"
      forcedValues:
        <<: *forcedBrand
      fields:
        <<: *billableCalls_fieldsLink
        options:
          title: _("Options")
          screens:
            billableCallsView_screen: true
          dialogs:
            tarificateCall_dialog: ${auth.brandFeatures.billing.enabled}
          default: billableCallsView_screen
      options:
        title: _("Options")
        dialogs:
          tarificateCall_dialog: true
        commands:
          exportBillableCallsToCsv_command: true
    billableCallsView_screen:
      <<: *billableCallsView_screenLink
      forcedValues:
        <<: *forcedBrand

  dialogs:
    <<: *billableCalls_dialogsLink

  commands: &exportBillableCallsToCsv_commandsLink
    exportBillableCallsToCsv_command: &exportBillableCallsToCsv_commandLink
      <<: *BillableCalls
      title: _("Export to CSV")
      label: true
      module: default
      controller: klear-custom-billable-calls
      action: export-to-csv
      class:  ui-silk-page-white-database
      forcedValues:
        "brand": ${auth.brandId}

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
