#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: residentialDevicesList_screen
  screens: &residentialDevices_screensLink
    residentialDevicesList_screen: &residentialDevicesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *ResidentialDevices
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Residential Device', 'Residential Devices', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/views/residential_devices.html"
      forcedValues:
        <<: *forcedBrand
      fields:
        blacklist: &residentialDevices_blacklistLink
          transport: true
          authNeeded: true
          password: true
          areaCode: true
          country: true
          allow: true
          disallow: true
          directMediaMethod: true
          updateCallerid: true
          fromDomain: true
          calleridUpdateHeader: true
          directConnectivity: true
          transformationRuleSet: true
          ip: true
          port: true
          language: true
          status: true
          ddiIn: true
        order:
          company: true
          name: true
          domain: true
          description: true
          outgoingDdi: true
          statusIcon: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
