#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: dDIsList_screen

  screens: &dDIs_screenLink
    dDIsList_screen: &dDIsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Ddis
      title: _("List of %s %2s", ngettext('DDI', 'DDIs', 0), "[format| (%parent%)]")
      class: ui-silk-lightning-go
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/views/ddis.html"
      forcedValues:
        <<: *forcedBrand
      order:
        field:
          - Ddi.country asc
          - Ddi.ddi asc
      fields:
        order: &dDIsFieldsOder_Link
          country: true
          ddi: true
          company: true
          carrier: true
        blacklist:
          externalCallFilter: true
          routeType: true
          target: true
          displayName: true
          user: true
          fax: true
          ivr: true
          huntGroup: true
          ddie164: true
          brand: true
          conferenceRoom: true
          recordCalls: true
          friendValue: true
          queue: true
          residentialDevice: true
          language: true
          conditionalRoute: true
          retailAccount: true
staging: 
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
