#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: callCsvReportsView_screen
  screens: &callCsvReports_screensLink
    callCsvReportsList_screen: &callCsvReportsList_screenLink
      controller: list
      order:
        field:
          - CallCsvReport.createdOn
        type: desc
      pagination:
        items: 25
      <<: *CallCsvReports
      class: ui-silk-report-clock
      title: _("List of %s %2s", ngettext('Call CSV report', 'Call CSV reports', 0), "[format| (%parent%)]")
      fields: &callCsvReports_fieldsLink
        blacklist:
          company: true
        order:
          csv: 1
          inDate: 1
          outDate: 1
          createdOn: 1
          sentTo: 1
        options:
          title: _("Options")
          screens:
            callCsvReportsView_screen: true
          dialogs:
            callCsvReportsDel_dialog: false
          default: callCsvReportsEdit_screen
      options:
        title: _("Options")
        dialogs:
          callCsvReportsDel_dialog: true

    callCsvReportsView_screen: &callCsvReportsView_screenLink
      <<: *CallCsvReports
      controller: edit
      disableSave: true
      class: ui-silk-eye
      label: false
      title: _("Edit %s %2s", ngettext('Call CSV report', 'Call CSV reports', 1), "[format| (%item%)]")
      fields: &callCsvReports_fieldsLink
        blacklist:
          company: true
        order:
          csv: 1
          createdOn: 1
          inDate: 1
          outDate: 1
          sentTo: 1
      fixedPositions:
        group0:
          colsPerRow: 12
          fields:
            csv: 6
            createdOn: 6
            inDate: 6
            outDate: 6
            sentTo: 6

  dialogs: &callCsvReports_dialogsLink
    callCsvReportsDel_dialog: &callCsvReportsDel_dialogLink
      <<: *CallCsvReports
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Call CSV report', 'Call CSV reports', 1))
      description: _("Do you want to delete this %s?", ngettext('Call CSV report', 'Call CSV reports', 1))
      message: _("%s successfully deleted.", ngettext('Call CSV report', 'Call CSV reports', 1))
      multiItem: 1
      labelOnList: 1

  commands: &callCsvReports_commandsLink
    callCsvReportsCsvDownload_command: &callCsvReportsCsvDownload_commandLink
      <<: *CallCsvReports
      controller: File
      action: force-download
      mainColumn: csv
      class: ui-silk-bullet-disk
    callCsvReportsCsvUpload_command: &callCsvReportsCsvUpload_commandLink
      <<: *CallCsvReports
      controller: File
      action: upload
      mainColumn: csv
    callCsvReportsCsvPreview_command: &callCsvReportsCsvPreview_commandLink
      <<: *CallCsvReports
      controller: File
      action: preview
      mainColumn: csv
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
