#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include CallCsvReportsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: callCsvSchedulersList_screen
  screens: &callCsvSchedulers_screensLink
    callCsvSchedulersList_screen: &callCsvSchedulersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *CallCsvSchedulers
      class: ui-silk-report-clock
      title: _("List of %s %2s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/calls/call_csv_schedulers.html"
      rawCondition: "CallCsvScheduler.brand is NULL"
      forcedValues:
        self::brand: null
        <<: *forcedCompany
      fields: &callCsvSchedulers_fieldsLink
        blacklist:
          brand: true
          callCsvNotificationTemplate: true
        order: &callCsvSchedulers_orderLink
          id: true
          name: true
          frequency: true
          unit: true
          email: true
          lastExecution: true
          nextExecution: true
        options:
          title: _("Options")
          screens:
            callCsvSchedulersEdit_screen: true
            callCsvReportsList_screen: true
          dialogs:
            callCsvSchedulersDel_dialog: true
          default: callCsvSchedulersEdit_screen
      options:
        title: _("Options")
        screens:
          callCsvSchedulersNew_screen: true
        dialogs:
          callCsvSchedulersDel_dialog: true

    callCsvSchedulersNew_screen: &callCsvSchedulersNew_screenLink
      <<: *CallCsvSchedulers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 0), "[format| (%parent%)]")
      forcedValues:
        self::brand: null
        <<: *forcedCompany
      shortcutOption: N
      fields:
        blacklist: &callCsvSchedulersNew_blacklist
          lastExecution: true
          nextExecution: true
          callCsvNotificationTemplate: true
        order:
          name: 1
          email: 1
          callCsvNotificationTemplate: 1
          frequency: 1
          unit: 1
          nextExecution: 1
          lastExecution: 1
      fixedPositions: &callCsvSchedulersFixedPositions_Link
        group0:
          label: _("Basic Information")
          colsPerRow: 2
          fields:
            name: 1
            company: 1
            email: 1
            callCsvNotificationTemplate: 1
        group1:
          label: _("Time Information")
          colsPerRow: 2
          fields:
            frequency: 1
            unit: 1
            nextExecution: 1
            lastExecution: 1

    callCsvSchedulersEdit_screen: &callCsvSchedulersEdit_screenLink
      <<: *CallCsvSchedulers
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1), "[format| (%item%)]")
      forcedValues:
        self::brand: null
        <<: *forcedCompany
      fields:
        blacklist: &callCsvSchedulersEdit_blacklist
          callCsvNotificationTemplate: true
      fixedPositions:
        <<: *callCsvSchedulersFixedPositions_Link

    # CallCsvReports
    <<: *callCsvReports_screensLink
    callCsvReportsList_screen:
      <<: *callCsvReportsList_screenLink
      filterField: callCsvScheduler
      parentOptionCustomizer:
        - recordCount
    callCsvReportsView_screen:
      <<: *callCsvReportsView_screenLink
      filterField: callCsvScheduler

  dialogs: &callCsvSchedulers_dialogsLink
    callCsvSchedulersDel_dialog: &callCsvSchedulersDel_dialogLink
      <<: *CallCsvSchedulers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1))
      description: _("Do you want to delete this %s?", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1))
      message: _("%s successfully deleted.", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1))
      multiItem: 1
      labelOnList: 1

    # CallCsvReports
    <<: *callCsvReports_dialogsLink

  commands: &callCsvSchedulers__commandsLink
    <<: *callCsvReports_commandsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
