#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include RatingPlansList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: ratingPlanGroupsList_screen
  screens: &ratingPlanGroups_screensLink
    ratingPlanGroupsList_screen: &ratingPlanGroupsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RatingPlanGroups
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Rating plan', 'Rating plans', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/billing/rating_plans.html"
      forcedValues:
        <<: *forcedBrand
      fields: &ratingPlanGroups_fieldsLink
        order:
          tag: true
          name: true
          description: true
        options:
          title: _("Options")
          screens:
            ratingPlanGroupsEdit_screen: true
            ratingPlansList_screen: true
          dialogs:
            ratingPlanGroupsDel_dialog: true
          default: ratingPlanGroupsEdit_screen
      options:
        title: _("Options")
        screens:
          ratingPlanGroupsNew_screen: true
        dialogs:
          ratingPlanGroupsDel_dialog: true
          simulateBrandPlansCall_dialog: true

    ratingPlanGroupsNew_screen: &ratingPlanGroupsNew_screenLink
      <<: *RatingPlanGroups
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rating plan', 'Rating plans', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fixedPositions: &ratingPlanGroupsFixedPositions_Link
        group1:
          colsPerRow: 9
          fields:
            name: 5
            description: 8
            currency: 4

    ratingPlanGroupsEdit_screen: &ratingPlanGroupsEdit_screenLink
      <<: *RatingPlanGroups
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Rating plan', 'Rating plans', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions:
        <<: *ratingPlanGroupsFixedPositions_Link

    # RatingPlans:
    <<: *ratingPlans_screensLink
    ratingPlansList_screen:
      <<: *ratingPlansList_screenLink
      filterField: ratingPlanGroup
      parentOptionCustomizer:
        - recordCount
    ratingPlansNew_screen:
      <<: *ratingPlansNew_screenLink
      filterField: ratingPlanGroup
    ratingPlansEdit_screen:
      <<: *ratingPlansEdit_screenLink
      filterField: ratingPlanGroup

  dialogs: &ratingPlanGroups_dialogsLink
    ratingPlanGroupsDel_dialog: &ratingPlanGroupsDel_dialogLink
      <<: *RatingPlanGroups
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rating plan', 'Rating plans', 1))
      description: _("Do you want to delete this %s?", ngettext('Rating plan', 'Rating plans', 1))
      message: _("%s successfully deleted.", ngettext('Rating plan', 'Rating plans', 1))
      multiItem: 1
      labelOnList: 1

    simulateBrandPlansCall_dialog: &simulateBrandPlansCall_dialogLink
      <<: *DestinationRates
      module: default
      title: _("Simulate a call")
      label: false
      labelOnEdit: false
      labelOnList: true
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-tarificator
      action: test-brand-plans
      class:  ui-silk-telephone

    # RatingPlan dialogs:
    <<: *ratingPlans_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
