imports:
  - { resource: "@CoreBundle/Resources/config/autoload.yml" }
  - { resource: '@CoreBundle/Resources/config/services/entities.yml' }
  - { resource: '@CoreBundle/Resources/config/services/infraestructure.yml' }
  - { resource: "@CoreBundle/Resources/config/services/path_resolvers.yml" }
  - { resource: "@CoreBundle/Resources/config/services/assemblers.yml" }
  - { resource: "@CoreBundle/Resources/config/services/domain.yml" }
  - { resource: "@CoreBundle/Resources/config/services/events.yml" }
  - { resource: "@CoreBundle/Resources/config/services/application.yml" }
  - { resource: '@CoreBundle/Resources/config/lifecycle.yml' }
  - { resource: '@CoreBundle/Resources/config/model.yml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Symfony\EventListener\DomainExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
