# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  BillableCallController:
    class: "BillableCallController"
  InvoiceSchedulerController:
    class: "InvoiceSchedulerController"
  CallCsvController:
    class: "CallCsvController"
