Ivoz\Kam\Domain\Model\Rtpengine\RtpengineAbstract:
  type: mappedSuperclass
  indexes:
    rtpengine_mediaRelaySetsId:
      columns:
        - mediaRelaySetsId
  uniqueConstraints:
    rtpengine_nodes:
      columns:
        - setid
        - url
  fields:
    setid:
      type: integer
      nullable: false
      size: 10
      options:
        fixed: false
        default: 0
    url:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 1
    disabled:
      type: boolean
      nullable: false
      options:
        default: '0'
        unsigned: false
    stamp:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
    description:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
  manyToOne:
    mediaRelaySet:
      targetEntity: \Ivoz\Provider\Domain\Model\MediaRelaySet\MediaRelaySetInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        mediaRelaySetsId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
