Ivoz\Kam\Domain\Model\TrunksLcrRule\TrunksLcrRuleAbstract:
  type: mappedSuperclass
  indexes:
    lcrRule_lcr_id:
      columns:
        - lcr_id
  fields:
    lcrId:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 1
      column: lcr_id
    prefix:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
    fromUri:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: from_uri
    requestUri:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
      column: request_uri
    mtTvalue:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: mt_tvalue
    stopper:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 0
    enabled:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 1
  manyToOne:
    routingPattern:
      targetEntity: \Ivoz\Provider\Domain\Model\RoutingPattern\RoutingPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: lcrRules
      joinColumns:
        routingPatternId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    routingPatternGroupsRelPattern:
      targetEntity: \Ivoz\Provider\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        routingPatternGroupsRelPatternId:
          referencedColumnName: id
          onDelete: cascade
          nullable: true
      orphanRemoval: false
    outgoingRouting:
      targetEntity: \Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRoutingInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: lcrRules
      joinColumns:
        outgoingRoutingId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
