Ivoz\Kam\Domain\Model\TrunksLcrRuleTarget\TrunksLcrRuleTargetAbstract:
  type: mappedSuperclass
  indexes:
    lcrRuleTarget_lcr_id:
      columns:
        - lcr_id
  fields:
    lcrId:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 1
      column: lcr_id
    priority:
      type: smallint
      nullable: false
      options:
        unsigned: true
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 1
  manyToOne:
    rule:
      targetEntity: \Ivoz\Kam\Domain\Model\TrunksLcrRule\TrunksLcrRuleInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        rule_id:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    gw:
      targetEntity: \Ivoz\Kam\Domain\Model\TrunksLcrGateway\TrunksLcrGatewayInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        gw_id:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    outgoingRouting:
      targetEntity: \Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRoutingInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: lcrRuleTargets
      joinColumns:
        outgoingRoutingId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
