Ivoz\Kam\Domain\Model\TrunksAddress\TrunksAddressAbstract:
  type: mappedSuperclass
  fields:
    grp:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 1
    ipAddr:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: ip_addr
    mask:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: 32
    port:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: 0
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
  oneToOne:
    ddiProviderAddress:
      targetEntity: \Ivoz\Provider\Domain\Model\DdiProviderAddress\DdiProviderAddressInterface
      inversedBy: trunksAddress
      fetch: LAZY
      joinColumn:
        name: ddiProviderAddressId
        referencedColumnName: id
        nullable: false
        onDelete: cascade
