Ivoz\Kam\Domain\Model\Trusted\TrustedAbstract:
  type: mappedSuperclass
  indexes:
    trusted_companyId:
      columns:
        - companyId
  uniqueConstraints:
    src_ip:
      columns:
        - src_ip
  fields:
    srcIp:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: src_ip
    proto:
      type: string
      nullable: true
      length: 4
      options:
        fixed: false
    fromPattern:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: from_pattern
    ruriPattern:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: ruri_pattern
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    description:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
    priority:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: 0
  manyToOne:
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
