Ivoz\Provider\Domain\Model\CallCsvScheduler\CallCsvSchedulerAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    CallCsvScheduler_name_brand:
      columns:
        - name
        - brandId
  fields:
    name:
      type: string
      nullable: false
      length: 40
      options:
        fixed: false
    unit:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
        comment: '[enum:day|week|month]'
        default: 'month'
    frequency:
      type: smallint
      nullable: false
      options:
        unsigned: true
    email:
      type: string
      nullable: false
      length: 140
      options:
        fixed: false
    lastExecution:
      type: datetime
      nullable: true
      column: lastExecution
    lastExecutionError:
      type: string
      nullable: true
      length: 300
      options:
        fixed: false
      column: lastExecutionError
    nextExecution:
      type: datetime
      nullable: true
      column: nextExecution
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    callCsvNotificationTemplate:
      targetEntity: \Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplateInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        callCsvNotificationTemplateId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
