Ivoz\Provider\Domain\Model\CallCsvReport\CallCsvReportAbstract:
  type: mappedSuperclass
  embedded:
    csv:
      class: Csv
      columnPrefix: false
  fields:
    sentTo:
      type: string
      nullable: false
      length: 250
      options:
        fixed: false
        default: ''
      column: sentTo
    inDate:
      type: datetime
      nullable: false
      column: inDate
    outDate:
      type: datetime
      nullable: false
      column: outDate
    createdOn:
      type: datetime
      nullable: false
      column: createdOn
  manyToOne:
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    callCsvScheduler:
      targetEntity: \Ivoz\Provider\Domain\Model\CallCsvScheduler\CallCsvSchedulerInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        callCsvSchedulerId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false