Ivoz\Provider\Domain\Model\Carrier\CarrierAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    carrier_nameBrand:
      columns:
        - name
        - brandId
  fields:
    description:
      type: string
      nullable: false
      length: 500
      options:
        fixed: false
        default: ''
    name:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
    externallyRated:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
      column: externallyRated
    balance:
      type: decimal
      nullable: true
      precision: 10
      scale: 4
      options:
        default: 0
    calculateCost:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
      column: calculateCost
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    transformationRuleSet:
      targetEntity: \Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSetInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        transformationRuleSetId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    currency:
      targetEntity: \Ivoz\Provider\Domain\Model\Currency\CurrencyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        currencyId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
