Ivoz\Provider\Domain\Model\DestinationRateGroup\DestinationRateGroupAbstract:
  type: mappedSuperclass
  embedded:
    name:
      class: Name
      columnPrefix: false
    description:
      class: Description
      columnPrefix: false
    file:
      class: File
      columnPrefix: false
  fields:
    status:
      type: string
      nullable: true
      length: 20
      options:
        fixed: false
        comment: '[enum:waiting|inProgress|imported|error]'
        default: null
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    currency:
      targetEntity: \Ivoz\Provider\Domain\Model\Currency\CurrencyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        currencyId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false