Ivoz\Provider\Domain\Model\HolidayDate\HolidayDateAbstract:
  type: mappedSuperclass
  fields:
    name:
      column: name
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    eventDate:
      type: date
      nullable: false
      column: eventDate
    wholeDayEvent:
      type: boolean
      nullable: false
      options:
        default: '1'
      column: wholeDayEvent
    timeIn:
      type: time
      nullable: true
      column: timeIn
    timeOut:
      type: time
      nullable: true
      column: timeOut
    routeType:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
        comment: '[enum:number|extension|voicemail]'
      column: routeType
    numberValue:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
      column: numberValue
  manyToOne:
    calendar:
      targetEntity: \Ivoz\Provider\Domain\Model\Calendar\CalendarInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: holidayDates
      joinColumns:
        calendarId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    locution:
      targetEntity: \Ivoz\Provider\Domain\Model\Locution\LocutionInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        locutionId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    extension:
      targetEntity: \Ivoz\Provider\Domain\Model\Extension\ExtensionInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        extensionId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    voiceMailUser:
      targetEntity: \Ivoz\Provider\Domain\Model\User\UserInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        voiceMailUserId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    numberCountry:
      targetEntity: \Ivoz\Provider\Domain\Model\Country\CountryInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        numberCountryId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false