Ivoz\Provider\Domain\Model\NotificationTemplateContent\NotificationTemplateContentAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    notificationTemplateContent_language_unique:
      columns:
        - notificationTemplateId
        - languageId
  fields:
    fromName:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: fromName
    fromAddress:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: fromAddress
    subject:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
    body:
      type: text
      nullable: false
      length: 65535
      options:
        fixed: false
    bodyType:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
        default: 'text/plain'
        comment: '[enum:text/plain|text/html]'
      column: bodyType
  manyToOne:
    notificationTemplate:
      targetEntity: \Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplateInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: contents
      joinColumns:
        notificationTemplateId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    language:
      targetEntity: \Ivoz\Provider\Domain\Model\Language\LanguageInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        languageId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false