Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRoutingAbstract:
  type: mappedSuperclass
  fields:
    type:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        default: group
    priority:
      type: smallint
      nullable: false
      options:
        unsigned: true
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 1
    routingMode:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
        comment: '[enum:static|lcr]'
        default: 'static'
      column: routingMode
    prefix:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
    forceClid:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
      column: forceClid
    clid:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: outgoingRoutings
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: outgoingRoutings
      joinColumns:
        carrierId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    routingPattern:
      targetEntity: \Ivoz\Provider\Domain\Model\RoutingPattern\RoutingPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: outgoingRoutings
      joinColumns:
        routingPatternId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    routingPatternGroup:
      targetEntity: \Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroupInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: outgoingRoutings
      joinColumns:
        routingPatternGroupId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    routingTag:
      targetEntity: \Ivoz\Provider\Domain\Model\RoutingTag\RoutingTagInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: outgoingRoutings
      joinColumns:
        routingTagId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    clidCountry:
      targetEntity: \Ivoz\Provider\Domain\Model\Country\CountryInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        clidCountryId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
