Ivoz\Provider\Domain\Model\RatingPlanGroup\RatingPlanGroupAbstract:
  type: mappedSuperclass
  embedded:
    name:
      class: Name
      columnPrefix: false
    description:
      class: Description
      columnPrefix: false
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    currency:
      targetEntity: \Ivoz\Provider\Domain\Model\Currency\CurrencyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        currencyId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false