Ivoz\Provider\Domain\Model\ResidentialDevice\ResidentialDevice:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ResidentialDeviceDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: ResidentialDevices
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    psEndpoints:
      targetEntity: Ivoz\Ast\Domain\Model\PsEndpoint\PsEndpointInterface
      mappedBy: residentialDevice
    ddis:
      targetEntity: Ivoz\Provider\Domain\Model\Ddi\DdiInterface
      mappedBy: residentialDevice
    callForwardSettings:
      targetEntity: Ivoz\Provider\Domain\Model\CallForwardSetting\CallForwardSettingInterface
      mappedBy: residentialDevice
