Ivoz\Provider\Domain\Model\RetailAccount\RetailAccountAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    retailAccount_name_brand:
      columns:
      - name
      - brandId
  fields:
    name:
      type: string
      nullable: false
      length: 65
      options:
        fixed: false
    description:
      type: string
      nullable: false
      length: 500
      options:
        fixed: false
        default: ''
    transport:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
        comment: '[enum:udp|tcp|tls]'
    ip:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
    port:
      type: smallint
      nullable: true
      options:
        unsigned: true
    password:
      type: string
      nullable: true
      length: 64
      options:
      fixed: false
    fromDomain:
      type: string
      nullable: true
      length: 190
      options:
        fixed: false
      column: fromDomain
    directConnectivity:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        comment: '[enum:yes|no]'
        default: 'yes'
      column: directConnectivity
    ddiIn:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        comment: '[enum:yes|no]'
        default: 'yes'
      column: ddiIn
  manyToOne:
    brand:
      targetEntity: Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: residentialDevices
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    domain:
      targetEntity: \Ivoz\Provider\Domain\Model\Domain\DomainInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: residentialDevices
      joinColumns:
        domainId:
          domainId: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    company:
      targetEntity: Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    transformationRuleSet:
      targetEntity: \Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSetInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        transformationRuleSetId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    outgoingDdi:
      targetEntity: Ivoz\Provider\Domain\Model\Ddi\DdiInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        outgoingDdiId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
