########################################
## Raw
########################################
Ivoz\Provider\Domain\Model\Brand\Brand:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        id:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Brand\Invoice:
Ivoz\Provider\Domain\Model\Brand\Logo:
Ivoz\Provider\Domain\Model\Administrator\Administrator:
  attributes:
    access_control: '"ROLE_COMPANY_ADMIN" in roles'
    read_access_control:
      ROLE_COMPANY_ADMIN:
        id:
          eq: "user.getId()"
      ROLE_BRAND_ADMIN:
        or:
          - company:
              in: "companyRepository.getSupervisedCompanyIdsByAdmin(user)"
          - brand:
              eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\ApplicationServer\ApplicationServer:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\BrandService\BrandService:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\BrandUrl\BrandUrl:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Country\Name:
Ivoz\Provider\Domain\Model\Country\Zone:
Ivoz\Provider\Domain\Model\Country\Country:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
Ivoz\Provider\Domain\Model\Domain\Domain:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Feature\Feature:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrand:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        brand:
          eq: "user.getBrand().getId()"
Ivoz\Provider\Domain\Model\Language\Language:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
Ivoz\Provider\Domain\Model\Language\Name:
Ivoz\Provider\Domain\Model\MediaRelaySet\MediaRelaySet:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\ProxyTrunk\ProxyTrunk:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\ProxyUser\ProxyUser:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Service\Service:
  itemOperations:
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\TerminalManufacturer\TerminalManufacturer:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\TerminalModel\TerminalModel:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Timezone\Timezone:
  itemOperations:
    put: ~
    delete: ~
  collectionOperations:
    post: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
