imports:
  - { resource: parameters.yml }

parameters:
    locale: en

framework:
  #esi: ~
  #translator: { fallbacks: ['%locale%'] }
  secret: '%secret%'
  router:
    resource: '%kernel.root_dir%/config/routing.yml'
    strict_requirements: ~
  templating:
    engines: ['twig']
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: false }
  serializer:
    enabled: true
  default_locale: '%locale%'
  trusted_hosts: ~
  trusted_proxies: ~
  session:
    # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id:  session.handler.native_file
    save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
  fragments: ~
  http_method_override: true
  assets: ~
  php_errors:
    log: true

# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
#  paths:
#    This must be set on application
#    '../views': ApiBundle

nelmio_cors:
  paths:
    '^/':
      allow_origin: ['*']
      allow_headers:
        - 'authorization'
        - 'content-type'
        - 'request-date'
      expose_headers:
        - 'Link'
        - 'X-First-Page'
        - 'X-Next-Page'
        - 'X-Last-Page'
        - 'X-Total-Items'
        - 'X-Total-Pages'
      allow_methods:
        - 'POST'
        - 'PUT'
        - 'GET'
        - 'DELETE'
      max_age: 3600
