# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
  - { resource: "@CoreBundle/Resources/config/services.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Worker\Multimedia:
    public: true
    arguments:
      $logger: '@logger'

  Worker\Rates:
    public: true
    arguments:
      $em: '@=service("doctrine.orm.entity_manager")'
      $logger: '@logger'

  Worker\Invoices:
    public: true

  Worker\Cgrates:
    public: true

  Worker\Xmlrpc:
    public: true
    arguments:
      $logger: '@logger'